feat: Implementing security features
depromeet/11th_5team pull request #9
Opened 2022-04-11 11:10 UTC by rere950303

token inspection before dispatcher servlet is performed through Interceptor. If invalid, redirect to refresh; if the refresh token is valid, issue a new token; if invalid, throw a 401 error

### 🔖 ISSUE 종류를 선택하세요

- [x] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Release
- [ ] Misc (docs, test, style, ...)

### 🔖 내용
인터셉터를 통한 security 구현

2022-04-11 15:14 UTC, zkdlu requested changes

2022-04-12 10:03 UTC, rere950303 commented on components/module-security/build.gradle
> +    implementation project(':components:support-jwt')
저도 이걸로 삽질했는데...방법 알려주셔서 감사합니다>!

2022-04-12 10:03 UTC, rere950303 commented on components/module-security/src/main/java/depromeet/ohgzoo/iam/security/config/WebConfig.java
> +package depromeet.ohgzoo.iam.security.config;
저는 환경변수로 받을 생각만 했는데 그냥 app모듈에 넣는게 더 좋을것 같네요!!

2022-04-12 10:05 UTC, rere950303 commented on components/module-security/src/main/java/depromeet/ohgzoo/iam/security/dto/AuthToken.java
> +public class AuthToken {
저도 처음에 이것때문에 ouath2 모듈 의존성 주입받았다가 dto 하나때문에 의존성주입 받는건 아닌것 같아서 이렇게 했는데 별도 라이브러리 빼는건 생각 못했네요! 공통된 dto는 하나의 모듈로 분리 시킬까요??

2022-04-12 10:06 UTC, rere950303 commented on components/module-security/src/main/java/depromeet/ohgzoo/iam/security/controller/TokenRefreshController.java
> +public class TokenRefreshController {
토큰에 관한건 oauth가 더 맞는것 같다는 생각입니다 저도!

2022-04-14 11:00 UTC, closed without merging